name: Python package

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install linting dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 yapf
      - name: Lint with flake8
        run: flake8 --max-complexity 20 .
      - name: Format python codes with yapf
        run: yapf -r -d mmdet2trt/ demo/ tests/ tools/
